### ISSUE TITLE
Standardization for text

### ISSUE THREAD

**Issue by cha0sg0d** [personaelabs/noun-nyms#210]
- newlines don't seem to be working
- think about handling posts written in Markdown? If so, we might need previews like in Github?

**Comment by lsankar4033** [comment]
another example of a post that needed bullets: https://nouns.nymz.xyz/posts/0x273ec2b12012d893f40371178e549576b0b7b59e3f773e976084a5b159e11d8b

I think scoping this to *just* enabling bulleted lists (i.e. newlines) is sufficient here

**Comment by cha0sg0d** [comment]
Turns out
> By default, HTML collapses consecutive whitespace characters, including newlines, into a single space when rendering text content inside a <p> element.

**Comment by cha0sg0d** [comment]
> another example of a post that needed bullets: https://nouns.nymz.xyz/posts/0x273ec2b12012d893f40371178e549576b0b7b59e3f773e976084a5b159e11d8b
> 
> I think scoping this to _just_ enabling bulleted lists (i.e. newlines) is sufficient here

@lsankar4033 Inspecting this post with logging reveals that it doesn't have newlines.

> Shark - moribund. Lil Nouns - 10 people arguing with each other. Nouns Builder - slow rug governance attack and tax liability. Gnars - some cool skate themed work but no demand and not self sustaining. Purple is maybe the best one. What can we do?

**Comment by cha0sg0d** [comment]
<img width="559" alt="CleanShot 2023-06-26 at 18 12 41@2x" src="https://github.com/personaelabs/noun-nyms/assets/42984734/d5bd2782-cc71-465b-b15a-941e77654931">

But this post is fixed now: https://nouns.nymz.xyz/posts/0xed64dbc07a8745a4bec7f934f89402ad179173ea9a907dfd707ea583387a6f27
