### ISSUE TITLE
self-notifications are displayed

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/noun-nyms#241]
I don't know if this is desired behavior necessarily, but I see notifications when I comment in a thread that I originally started. These notifications feel like they're clogging up what I actually want to be seeing; just what other identities are posting.

Don't want to attach a screenshot b/c don't want to dox, but happy to elaborate more!

**Comment by cha0sg0d** [comment]
This is the correct behavior logically, but I see how it's not great UX. Is your preferred behavior that you only get notifications when anyone who is not one of your identities interacts with any post from your identities?
