### ISSUE TITLE
Setup analytics

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/noun-nyms#99]

**Comment by lsankar4033** [comment]
what do you think we should track? also any tooling preferences?

**Comment by DanTehrani** [comment]
@lsankar4033  We can get data in many ways, but I think a starting point is having a nice view of the database that'll help us polish our understanding of what's happening.  Had good experience using [Metabase](https://floorstandard.metabaseapp.com/) in previous projects (just give Metabase read-access to the db, and you can create dashboards from the data in the db)

We don't have to do this rn, and I think we should do this after launch!

**Comment by DanTehrani** [comment]
Tried Metabase. SQL is not expressive enough to learn about pseudonymity set sizes across time. And the app UI is nice enough to learn about what's going on, so we don't need a Metabase dashboard for Post/Upvotes either.

**Comment by lsankar4033** [comment]
sg
